### ISSUE TITLE
Change schema file location for GraphQL types code generation

### ISSUE THREAD

**Issue by andreysubbotin** [Amplicode/amplicode-frontend#144]
With Spring GraphQL - schema file is located under the directory: `\src\main\resources\graphql\schema.graphqls`
So schema property should be changed in `codegen.yml` to:
```
schema: ..\src\main\resources\graphql\schema.graphqls
```

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov This ticket is about the default path where the generator seeks for the schema file. Previously it was on the top level of the (Amplicode) project. Now it's moved to `src\main\resources\graphql\schema.graphqls`. If you attempt to create Frontend Module in [petclinic](https://github.com/Amplicode/amplicode-mvp-petclinic) it will fail because if won't find the schema.
