### ISSUE TITLE
Details screen doesn't check id === "new"

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#554]
Generator: 0.26.0
Project:

I generated normal entity, CRUD controller and Entity Management screen with List Component = List.

If I press "Create" in the list screen, then details screen opens and tries to load item with id = "new" from server.
[vacation.zip](https://github.com/Amplicode/amplicode-frontend/files/9270319/vacation.zip)
(so I get server error).

```
export function ProductDetails() {
  const intl = useIntl();
  useBreadcrumbItem(intl.formatMessage({ id: "screen.ProductDetails" }));

  const { recordId } = useParams();
  const navigate = useNavigate();

  if (recordId == null) throw new Error("recordId must be defined");
  const { loading: queryLoading, error: queryError, data } = useQuery(PRODUCT, {
    variables: {
      id: recordId
    }
  });

```

**Comment by vyacheslav-pushkin** [comment]
@alexbudarov This happens when user selects Edit mode but doesn't provide upsert mutation. As a result we generate entity list with "Create" button and a read-only details screen that doesn't have a capability of creating entities.

For now I have added a check in the generator, it will throw an error when it encounters this combination of parameters:

```
'Invalid combination of parameters. Edit mode was selected for entity list, but no upsert mutation was specified for entity details screen. ' +
  'Select a different mode if you want to create an entity list with a read-only details screen, ' +
  'or provide upsert mutation if you want to create an entity list with an editor.'
```

In future we can disallow this on protocol level by making upsert mutation mandatory if mode is "Edit". In order to do that, we can introduce a new answer parameter "requiredIf" which will function similarly to "showIf".
